### ISSUE TITLE
Unable to get this working in RN 0.60.3

### ISSUE THREAD

**Issue by aajkishore** [ismnoiet/react-native-range-slider#14]
I am unable to get this working. Here is what I tried.

1) When I DON'T run `react-native link react-native-range-slider`, the build succeeds, but I get ` "RangeSlider" was not found in the UIManager` error when I navigate to the screen where I am using RangeSlider.

2) When I run `react-native link react-native-range-slider` and then try to build the app, the build fails with this error.

`The following build commands failed:
	CompileC /Users/<APP_PATH>/Build/Intermediates.noindex/RangeSlider.build/Debug-iphonesimulator/RangeSlider.build/Objects-normal/x86_64/RangeSlider.o /Users/<APP_PATH>/node_modules/react-native-range-slider/ios/RangeSlider/RangeSlider.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler`

I am using the same code given in the [usage](https://github.com/ismnoiet/react-native-range-slider#usage) section.

I do see `RangeSlider.xcodeproj` in libraries, and `libRangeSlider.a` in link binary with libraries. I am using react native 0.60.3.

**Comment by hassanjallow** [comment]
I am having the same issue. Did you manage to get this working?

**Comment by aajkishore** [comment]
No.

**Comment by ismnoiet** [comment]
This is due to the new linking mechanism introduced in react native `0.60`.
A new upgrade is under development to support the latest RN version.

In the mean time you can use this module with react native`<0.60` without any issues.

**Comment by ismnoiet** [comment]
For those working with React Native version >= `0.60` you can use [fix_rn_0.60](https://github.com/ismnoiet/react-native-range-slider/tree/fix_rn_0.60) branch, until it is merged with master later on.
