### ISSUE TITLE
Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index'.

### ISSUE THREAD

**Issue by smnth90** [ismnoiet/react-native-range-slider#16]
I got this error when using this package in my Expo project.
Any fix on this?

**Comment by ismnoiet** [comment]
@smnth90  I didn't test the module in expo. I think expo needs extra config and usually has issues with modules that contain native code. I don't use expo, but If you want to submit a PR for expo support I will be happy to review it.
