### ISSUE TITLE
Help customize

### ISSUE THREAD

**Issue by dreamdev21** [ismnoiet/react-native-range-slider#2]
I want slider looks like this.
![capture](https://user-images.githubusercontent.com/29256561/41549237-78547d74-7325-11e8-893b-6dd57658a742.PNG)
I think this package is very similar I am looking for.
So please help customization based on this package.
Best.

**Comment by ismnoiet** [comment]
With the current version of the module you can achieve this UI, the only limitation for now is the color gradient between the `minimumSelectedValue` and `maximumSelectedValue`.

**Comment by dreamdev21** [comment]
Yes,
But on this package, handleBorderWidth and handleBorderColor props not working.
And Min, Max characters I need on slider range.

**Comment by dreamdev21** [comment]
<RangeSlider
                minValue={0}
                maxValue={10}
                tintColor={'#e8f0f3'}
                handleBorderWidth={20}
                handleBorderColor="#00b0cd"
                selectedMinimum={3}
                selectedMaximum={8}
                style={{ flex: 1, height: 70, backgroundColor: '#ffffff' }}
                onChange={ (data)=>{ console.log(data);} }
              />
![capture](https://user-images.githubusercontent.com/29256561/41549867-76b36fe6-7327-11e8-9f03-d493adce85de.PNG)
On my simulator seems like this.
Thanks.

**Comment by ismnoiet** [comment]
They are working correctly for me, hopefully tonight i can upload a working example, so people can play with.

**Comment by ismnoiet** [comment]
Try to use the latest version(`0.0.7` currently) and Here is a close example:

```
<RangeSlider
        tintColor="#e8f0f3"
        tintColorBetweenHandles="#30bbc6"
        minLabelColour="#b0b0b5"
        maxLabelColour="#b0b0b5"
        handleColor="#ffffff"
        minValue={0}
        maxValue={100}
        selectedMinimum={20}
        selectedMaximum={40}
        lineHeight={9.0}
        handleBorderWidth={4}
        handleBorderColor="#f1f5f6"
        handleDiameter={30}
        ...
/>
```
<img width="213" alt="screen shot 2018-06-20 at 6 33 37 am" src="https://user-images.githubusercontent.com/5025240/41639011-1eec21da-7454-11e8-91c4-e437761fa475.png">

Hopefully soon I will add some customization features as you mentioned, and pull requests are always welcomed.

**Comment by dreamdev21** [comment]
Thanks for your update.
Now, how can I disable out range min, max values?

**Comment by dreamdev21** [comment]
Any update?

**Comment by ismnoiet** [comment]
@webmasterdragon I will upload a new version soon with gradient colours and a single slider option.

**Comment by ismnoiet** [comment]
Hi @webmasterdragon, sorry I'm a little bit busy with work, but I was able to reproduce what you're looking for and you need to write some native code:

here is the screenshot:

<img width="253" alt="screen shot 2018-07-09 at 12 56 46 am" src="https://user-images.githubusercontent.com/5025240/42425298-2db334a6-8313-11e8-805a-57db838921ee.png">

Now let's see how to achieve that:

- Open `RangeSlider.xcodeproj/TTRangeSlider/TTRangeSlider.m` and remove the snippet of code in red box : 

<img width="963" alt="screen_shot_2018-07-09_at_1_02_02_am" src="https://user-images.githubusercontent.com/5025240/42425458-c5f14e68-8315-11e8-94fb-cba63c5eed0b.png">

- Then add the following code as a replacement for the deleted code:

```
   // add your desired colours here, it can be more than 2 colors.
    UIColor *leftColor = [UIColor colorWithRed:0.16 green:0.70 blue:0.80 alpha:1.0];
    UIColor *rightColor = [UIColor colorWithRed:0.93 green:0.94 blue:0.62 alpha:1.0];
    
    CAGradientLayer *theViewGradient = [CAGradientLayer layer];
    theViewGradient.colors = [NSArray arrayWithObjects: (id)leftColor.CGColor, (id)rightColor.CGColor, nil];
    theViewGradient.frame = self.bounds;
    
    theViewGradient.startPoint = CGPointMake(0, 0.5);
    theViewGradient.endPoint = CGPointMake(1.0, 0.5);
    
    self.sliderLineBetweenHandles = theViewGradient;
    [self.layer addSublayer:self.sliderLineBetweenHandles];
```

- Now on the JavaScript side use the following snippet of code to reproduce the example easily:
```
<View style={{ flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' }}>
          <RangeSlider
            tintColor="#e8f0f3"
            tintColorBetweenHandles="#30bbc6"
            minLabelColour="#b0b0b5"
            maxLabelColour="#b0b0b5"
            handleColor="#ffffff"
            minValue={0}
            maxValue={100}
            selectedMinimum={20}
            selectedMaximum={40}
            lineHeight={9.0}
            handleBorderWidth={4}
            handleBorderColor="#f1f5f6"
            handleDiameter={30}
            style={{ flex: 1, height: 70, padding: 10, backgroundColor: 'white' }}
            onChange={ (data)=>{ console.log(data);} }
          />
</View>
```

That is it.

If you know some objective-c it would be great if you can work on this and submit a PR and I will be happy to review it. Otherwise hopefully if I get time in the upcoming days I will add some additional features.

**Comment by dreamdev21** [comment]
Great!
It works for me and hope to add disable function asap.

**Comment by ismnoiet** [comment]
@webmasterdragon check the version `0.1.0`, it includes the possibility to use a normal slider with a single handle and a link to a working example.

If it works for you let me know so I can close this issue.

**Comment by dreamdev21** [comment]
Thank you for your update.

**Comment by ismnoiet** [comment]
You are welcome.
