### ISSUE TITLE
Does this module work on android?

### ISSUE THREAD

**Issue by Austyns** [ismnoiet/react-native-range-slider#3]
This is not an issue, just wanted to confirm if this works on android. Thank you

**Comment by ismnoiet** [comment]
@Austyns This module unfortunately doesn't work on android as stated on the documentation, but hopefully in the future I will find a way to port it to android.

**Comment by Er-rchydy** [comment]
@ismnoiet  can you please add support for Android

**Comment by ismnoiet** [comment]
@Er-rchydy currently I can't work on it, but hopefully in the near future I will get some time to add android support, otherwise PRs are appreciated.

**Comment by Er-rchydy** [comment]
@ismnoiet ok thanks. i've just started learning React Native recently, i have some time, so if you have some  resources about how to implement it on android please share it and if i got it to work i will push a PR.

**Comment by ismnoiet** [comment]
@Er-rchydy There is a lot of online resources for "how to create a react native module", just google it.
Here are some useful links and modules to help you with that:
- https://github.com/peggyrayzis/react-native-create-bridge
- https://github.com/frostney/react-native-create-library
- https://medium.com/@httpdeveloper/how-to-build-a-simple-react-native-custom-module-for-ios-and-android-from-scratch-a8efd31446f0

and I'm sure you will find a lot of other useful resources. 

Happy coding!
