### ISSUE TITLE
Help with setup in a Expo app

### ISSUE THREAD

**Issue by ghost** [ismnoiet/react-native-range-slider#4]
Hello there, I emailed you recently about the issue I had with setting this plugin up with my expo app.

Everything I have is pretty standard, and all other react-native-* plugins work fine.

I followed your documentation, installed it using npm, and linked it using the react-native command.

I then add the line to include this component in my js like so: `import RangeSlider from 'react-native-range-slider'`

I also went into the xcode project and implemented the manual linking steps as described in the docs you have linked.

At this point the app runs well, however, when I add the actual component on the page like so: 

```
<RangeSlider
    minValue={0}
    maxValue={100}
    tintColor={'#da0f22'}
    handleBorderWidth={1}
    handleBorderColor="#454d55"
    selectedMinimum={20}
    selectedMaximum={40}
    style={{ flex: 1, height: 70, padding: 10, backgroundColor: '#ddd' }}
    onChange={ (data)=>{ console.log(data);} }
  />
```
- the app does not load and I get this error:
<img width="474" alt="screen shot 2018-10-11 at 3 23 10 pm" src="https://user-images.githubusercontent.com/44070793/46828631-a5b28380-cd69-11e8-82af-95e6e6cd0bd7.png">

<img width="537" alt="screen shot 2018-10-11 at 3 25 59 pm" src="https://user-images.githubusercontent.com/44070793/46828771-00e47600-cd6a-11e8-8593-3add9b63bad1.png">

Sorry my emulator does not let me copy the full stack for some reason, but the screenshots contain it all.

I also have some logs in my console, but I'm not sure if they are helpful for you.
```

This error is located at:
    in n (at registerRootComponent.js:35)
    in r (at registerRootComponent.js:34)
    in t (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in t (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in t (at AppContainer.js:122)
    in r (at renderApplication.js:32)
- node_modules/react-native/Libraries/ReactNative/requireNativeComponent.js:103:2 in <unknown>
- node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:14127:6 in _a
- ... 20 more stack frames from framework internals
3:23:27 p.m.: Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
- node_modules/expo/src/logs/LogSerialization.js:173:9 in k
- node_modules/expo/src/logs/LogSerialization.js:19:0 in <unknown>
- ... 49 more stack frames from framework internals

```

I appreciate your help very much, and please let me know if you need any details from my end.

Cheers, and thanks for a great plugin!

**Comment by ismnoiet** [comment]
@ejdeha, please provide a link to a Github repo that I can use to reproduce your issue.

**Comment by mehranabi** [comment]
I have the same issue, Just installed your library in my Expo project and ran the application.
Then it showed this error:
`Native component for "RangeSlider" does not exist.`

**Comment by ghost** [comment]
@MehranAbghari thanks for submitting your issue. I wasn't sure how to provide a repo link for @ismnoiet. Perhaps you can help me out so we can show it to him and solve it together? Cheers!

**Comment by mehranabi** [comment]
Hello @ejdeha, Thanks for the reply! I'll be happy if it gets fixed.
I think it's very simple, He/She can reproduce that issue easily, BUT I'll create a repo when I find some free time.
And... Can I ask you Where are u from ?!

**Comment by ismnoiet** [comment]
After doing some research about expo I think you can't link and use react-native modules that have some native code (objective-c,Java etc) easily, instead you should use what they call [expoKit](https://docs.expo.io/versions/latest/guides/expokit.html), which is out of the scope of react-native.

If you want to test that for yourself it would be great, otherwise I suggest converting your project to react-native and my module should work effortlessly!.

Sorry to tell you this, but I'm not interested in investing time on expo due to its limitations, but I'm open to PRs if you can fix that for expo.
