### ISSUE TITLE
Ability to hide min and max labels

### ISSUE THREAD

**Issue by brad-lasecke** [ismnoiet/react-native-range-slider#6]
I don't see a way to completely hide the labels that appear above the min and max handlers. I can get around this by setting the label colors to the same color as my background, but thats not necessarily hidden. Can we add in a boolean prop like hideLabels to remove the labels from being rendered? Thanks

**Comment by ismnoiet** [comment]
Thanks @brad-lasecke for reporting that, `hideLabels` is now available in the new version `0.1.1` and can be enabled as in the following example:
```
<RangeSlider
    ...
    hideLabels={true}
    ...
/>
```
Please test the new version and let me know if we can close this issue.
Also don't forget to ⭐️this repo if you found this module helpful.
